name: notes_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  flutter_bloc: 8.1.3
  bloc: ^8.1.2
  meta: 1.10.0
  path: ^1.8.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "/Users/mostafaahmed/Documents/Flutter projects/notes_app/assets/1024.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
flutter:
  uses-material-design: true
